# Harmony Jekyll theme general configurations 

# Base URL
baseurl: /romaindso.github.io

# Site live URL
url: http://romaindso.github.io

# Localhost 
# url: http://127.0.0.1:4000  

# Harmony theme configuration. Please change accordingly.
harmony:
  name: romaindso.github.io
  # Little description about your site
  description: 
    meta_description: > # 
      Web developper based in France at Bordeaux, this is my place to share my coding experiences. I mainly talk about front-end development, NodeJS and other cool stuff.  
    basetheme: theme-base-01 # pre defined thmes are darken, blue-water, redish.
    author: # Author details
      name: Romain Durand Saint Omer
      email: romain.dso@gmail.com
      url: http://romaindso.github.io

  # Google Analytics key, leave blank to ignore
  google_analytics_key: UA-xxxx-x

  # Profile links, leave blank to ignore
  social: 
    github: romaindso
    twitter: romain_dso
    facebook:
    gplus: 
    dribble: 
    pinterest: 
  # Toggle disclaimer in footer
  show_disclaimer: false

# Conversion / Build settings 
markdown:    kramdown
# This is how you put pygments config in jekyll 2.0 instead of pygments: true
highlighter: pygments 

# Permalinks
permalink:        pretty

exclude: 
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock

# Sass conversion configs
sass:
    sass_dir: assets/css/_sass
    style: :compressed
